[package]
name = "aleo"
version = "0.1.0"
authors = ["The Aleo Team <hello@aleo.org>"]
edition = "2018"

[[bin]]
name = "accounts"
path = "accounts/src/main.rs"

[workspace]
members = ["accounts"]

[dependencies]
aleo-accounts = { path = "./accounts", version = "0.1.0" }
